### ISSUE TITLE
Hope it can support 1080 monitors, currently only supports 4k monitors, the installation experience is very bad

### ISSUE THREAD

**Issue by Iemixiao** [LinhNC/XPS9570-OpenCore#2]
Hope it can support 1080 monitors, currently only supports 4k monitors, the installation experience is very bad

**Comment by LinhNC** [comment]
If your laptop display is 1080p, you have to modify your config.plist:
- Find `uiscale` and change its value to `AQ==` 
- Find `dpcd-max-link-rate` and change its value to `CgAAAA==`
Hope will help. Thanks

**Comment by Iemixiao** [comment]
If I only modify these two contents, the screen after I boot up and log in will become very large.

**Comment by LinhNC** [comment]
> If I only modify these two contents, the screen after I boot up and log in will become very large.

You maybe need to remove the injected EID key
`<key>AAPL00,override-no-connect</key> `

**Comment by Iemixiao** [comment]
tks!!!!
